export const CONTROL_LIST_REQUEST = 'CONTROL_LIST_REQUEST';
export const CONTROL_LIST_SUCCESS = 'CONTROL_LIST_SUCCESS';
export const CONTROL_LIST_FAIL = 'CONTROL_LIST_FAIL';
export const CONTROL_LIST_RESET = 'CONTROL_LIST_RESET';

export const CONTROL_DETAILS_REQUEST = 'CONTROL_DETAILS_REQUEST';
export const CONTROL_DETAILS_SUCCESS = 'CONTROL_DETAILS_SUCCESS';
export const CONTROL_DETAILS_FAIL = 'CONTROL_DETAILS_FAIL';
export const CONTROL_DETAILS_RESET = 'CONTROL_DETAILS_RESET';

export const CONTROL_CREATE_REQUEST = 'CONTROL_CREATE_REQUEST';
export const CONTROL_CREATE_SUCCESS = 'CONTROL_CREATE_SUCCESS';
export const CONTROL_CREATE_FAIL = 'CONTROL_CREATE_FAIL';
export const CONTROL_CREATE_RESET = 'CONTROL_CREATE_RESET';

export const CONTROL_UPDATE_REQUEST = 'CONTROL_UPDATE_REQUEST';
export const CONTROL_UPDATE_SUCCESS = 'CONTROL_UPDATE_SUCCESS';
export const CONTROL_UPDATE_FAIL = 'CONTROL_UPDATE_FAIL';
export const CONTROL_UPDATE_RESET = 'CONTROL_UPDATE_RESET';

export const CONTROL_DELETE_REQUEST = 'CONTROL_DELETE_REQUEST';
export const CONTROL_DELETE_SUCCESS = 'CONTROL_DELETE_SUCCESS';
export const CONTROL_DELETE_FAIL = 'CONTROL_DELETE_FAIL';
export const CONTROL_DELETE_RESET = 'CONTROL_DELETE_RESET';

export const CONTROL_BYPACIENTE_REQUEST = 'CONTROL_BYPACIENTE_REQUEST';
export const CONTROL_BYPACIENTE_SUCCESS = 'CONTROL_BYPACIENTE_SUCCESS';
export const CONTROL_BYPACIENTE_FAIL = 'CONTROL_BYPACIENTE_FAIL';
export const CONTROL_BYPACIENTE_RESET = 'CONTROL_BYPACIENTE_RESET';
