export const GASTO_LIST_REQUEST = "GASTO_LIST_REQUEST";
export const GASTO_LIST_SUCCESS = "GASTO_LIST_SUCCESS";
export const GASTO_LIST_FAIL = "GASTO_LIST_FAIL";
export const GASTO_LIST_RESET = "GASTO_LIST_RESET";

export const GASTO_DETAILS_REQUEST = "GASTO_DETAILS_REQUEST";
export const GASTO_DETAILS_SUCCESS = "GASTO_DETAILS_SUCCESS";
export const GASTO_DETAILS_FAIL = "GASTO_DETAILS_FAIL";

export const GASTO_CREATE_REQUEST = "GASTO_CREATE_REQUEST";
export const GASTO_CREATE_SUCCESS = "GASTO_CREATE_SUCCESS";
export const GASTO_CREATE_FAIL = "GASTO_CREATE_FAIL";
export const GASTO_CREATE_RESET = "GASTO_CREATE_RESET";

export const GASTO_REVIEW_CREATE_REQUEST = "GASTO_REVIEW_CREATE_REQUEST";
export const GASTO_REVIEW_CREATE_SUCCESS = "GASTO_REVIEW_CREATE_SUCCESS";
export const GASTO_REVIEW_CREATE_FAIL = "GASTO_REVIEW_CREATE_FAIL";
export const GASTO_REVIEW_CREATE_RESET = "GASTO_REVIEW_CREATE_RESET";

export const GASTO_UPDATE_REQUEST = "GASTO_UPDATE_REQUEST";
export const GASTO_UPDATE_SUCCESS = "GASTO_UPDATE_SUCCESS";
export const GASTO_UPDATE_FAIL = "GASTO_UPDATE_FAIL";
export const GASTO_UPDATE_RESET = "GASTO_UPDATE_RESET";

export const GASTO_DELETE_REQUEST = "GASTO_DELETE_REQUEST";
export const GASTO_DELETE_SUCCESS = "GASTO_DELETE_SUCCESS";
export const GASTO_DELETE_FAIL = "GASTO_DELETE_FAIL";
export const GASTO_DELETE_RESET = "GASTO_DELETE_RESET";

export const GASTO_UPDATE_EXISTENCIA_REQUEST = "GASTO_UPDATE_EXISTENCIA_REQUEST";
export const GASTO_UPDATE_EXISTENCIA_SUCCESS = "GASTO_UPDATE_EXISTENCIA_SUCCESS";
export const GASTO_UPDATE_EXISTENCIA_FAIL = "GASTO_UPDATE_EXISTENCIA_FAIL";
export const GASTO_UPDATE_EXISTENCIA_RESET = "GASTO_UPDATE_EXISTENCIA_RESET";

export const GASTO_BYCODE_REQUEST = "GASTO_BYCODE_REQUEST";
export const GASTO_BYCODE_SUCCESS = "GASTO_BYCODE_SUCCESS";
export const GASTO_BYCODE_FAIL = "GASTO_BYCODE_FAIL";
export const GASTO_BYCODE_RESET = "GASTO_BYCODE_RESET";

export const GASTO_ONLY_CODES_REQUEST = "GASTO_ONLY_CODES_REQUEST";
export const GASTO_ONLY_CODES_SUCCESS = "GASTO_ONLY_SUCCESS";
export const GASTO_ONLY_CODES_FAIL = "GASTO_ONLY_FAIL";

export const GASTO_ALL_REQUEST = "GASTO_ALL_REQUEST";
export const GASTO_ALL_SUCCESS = "GASTO_ALL_SUCCESS";
export const GASTO_ALL_FAIL = "GASTO_ALL_FAIL";
