export const listaLabs = [
  "",
  "Laboratorio1 (Dr. del Laboratorio)",
  "Laboratorio1 (Dr. del Laboratorio)",
  "Laboratorio1 (Dr. del Laboratorio)",
  "Laboratorio1 (Dr. del Laboratorio)",
  "Laboratorio1 (Dr. del Laboratorio)",
  "Laboratorio1 (Dr. del Laboratorio)",
  "Laboratorio1 (Dr. del Laboratorio)",
  "Laboratorio1 (Dr. del Laboratorio)",
  "Laboratorio1 (Dr. del Laboratorio)",
  "Laboratorio1 (Dr. del Laboratorio)",
 
];


export const listaTipos = [
  "",
  "Alta Gama",
  "Casual",
  "Deportivo",
  "Sandalias",
  "Camisa",
  "Franela",
  "Short",
  "Mono",
  "Chemise",
  "Sweater",
  "Otro",
];

export const categorias = [
  "",
  "Nomina",
  "Suministros",
  "Repuestos",
  "Aceite",
  "Servicio",
  "soporte",
  "Mecanico",
  "Alquileres",
  "Reparaciones",
  "Mano de Obra",
  "Prestamos",
  "Taxis",
  "Comidas y Refrigerios",
  "Pago Publicidad",
  "Pago Internet",
  "Pago Telefonia",
  "Pago Gasolina",
  "Otros Gastos",
  "Intercambio Publicitario",
  "Pago a Influencers",
  "Edicion de Videos",
  "Redes Sociales",
  "Ferreteria",
];

export const nombres = [
  " ",
  "Rony Paul",
  "Ronald Paul",
  "Franklin Bolivar",
  "Omar Bachir",
  "Reinaldo Perdomo",
  "Margaris Blanco",
  "Nayluz Lopez",
  "Enderson Montilla",
  "Alejandro Bolivar",
  "Yefraini",
  "Manuel Martinez",
];

export const selectFormapago = [
  "",
  "Efectivo US$",
  "Efectivo Bs.",
  "Efectivo Euros",
  "Pago Movil",
  "Transferencia",
  "Zelle",
  "Tarjeta Debito",
  "Tarjeta Visa",
  "Tarjeta Master",
  "TDC Internacional",
  "Intercambio",
  "Pago Pendiente",
  "Credito",
  "Sin Pago",
];

export const selectBancos = [
  "",
  "Plaza",
  "Banesco",
  "Venezuela",
  "Bicentenario",
  "Mercantil",
  "Bancamiga",
  "Banplus",
  "Provincial",
  "Caribe",
  "BNC",
  "Vzlano Cdto",
  "Tesoro",
];
