export const listaLabs = ["LABORATORIO ALCIDE", "LABORATORIO 2", "LABORATORIO 3", "LABORATORIO 4", "LABORATORIO 5"];

export const categorias = [
  "",
  "Nomina",
  "Suministros",
  "Repuestos",
  "Aceite",
  "Servicio",
  "soporte",
  "Mecanico",
  "Alquileres",
  "Reparaciones",
  "Mano de Obra",
  "Prestamos",
  "Taxis",
  "Comidas y Refrigerios",
  "Pago Publicidad",
  "Pago Internet",
  "Pago Telefonia",
  "Pago Gasolina",
  "Otros Gastos",
  "Intercambio Publicitario",
  "Pago a Influencers",
  "Edicion de Videos",
  "Redes Sociales",
  "Ferreteria",
];

export const nombres = [
  " ",
  "Rony Paul",
  "Ronald Paul",
  "Franklin Bolivar",
  "Omar Bachir",
  "Reinaldo Perdomo",
  "Margaris Blanco",
  "Nayluz Lopez",
  "Enderson Montilla",
  "Alejandro Bolivar",
  "Yefraini",
  "Manuel Martinez",
];

export const selectFormapago = [
  "",
  "Efectivo US$",
  "Efectivo Bs.",
  "Efectivo Euros",
  "Pago Movil",
  "Transferencia",
  "Zelle",
  "Tarjeta Debito",
  "Tarjeta Visa",
  "Tarjeta Master",
  "TDC Internacional",
  "Intercambio",
  "Pago Pendiente",
  "Credito",
  "Sin Pago",
];

export const selectBancos = [
  "",
  "Plaza",
  "Banesco",
  "Venezuela",
  "Bicentenario",
  "Mercantil",
  "Bancamiga",
  "Banplus",
  "Provincial",
  "Caribe",
  "BNC",
  "Vzlano Cdto",
  "Tesoro",
];

export const tipoLab = [
  " ",
  "PROTESIS FIJA (corona metal porcelana)",
  "PROTESIS FIJA (corona metal porcelana dento-gingival)",
  "PROTESIS FIJA (corona metal porcelana sobre implante)",
  "PROTESIS FIJA (corona metal porcelana sobre implante atornillado)",
  "PROTESIS FIJA (corona metal porcelana con hombro ceramico)",
  "PROTESIS FIJA (corona funda metalica)",
  "PROTESIS FIJA (corona con frente estetico)",
  "PROTESIS FIJA (puente maryland)",
  "PROTESIS FIJA (perno colocado directo)",
  "PROTESIS FIJA (perno colocado indirecto)",
  "PROTESIS FIJA (encerado funcional por pieza)",
  "PROTESIS FIJA (vaciado de impresion)",
];
