export const listaLabs = ["LABORATORIO ALCIDE", "LABORATORIO 2", "LABORATORIO 3", "LABORATORIO 4", "LABORATORIO 5"];

export const categorias = [
  "",
  "Nomina",
  "Suministros",
  "Repuestos",
  "Aceite",
  "Servicio",
  "soporte",
  "Mecanico",
  "Alquileres",
  "Reparaciones",
  "Mano de Obra",
  "Prestamos",
  "Taxis",
  "Comidas y Refrigerios",
  "Pago Publicidad",
  "Pago Internet",
  "Pago Telefonia",
  "Pago Gasolina",
  "Otros Gastos",
  "Intercambio Publicitario",
  "Pago a Influencers",
  "Edicion de Videos",
  "Redes Sociales",
  "Ferreteria",
];

export const nombres = [
  " ",
  "Rony Paul",
  "Ronald Paul",
  "Franklin Bolivar",
  "Omar Bachir",
  "Reinaldo Perdomo",
  "Margaris Blanco",
  "Nayluz Lopez",
  "Enderson Montilla",
  "Alejandro Bolivar",
  "Yefraini",
  "Manuel Martinez",
];

export const selectFormapago = [
  "",
  "Efectivo US$",
  "Efectivo Bs.",
  "Efectivo Euros",
  "Pago Movil",
  "Transferencia",
  "Zelle",
  "Tarjeta Debito",
  "Tarjeta Visa",
  "Tarjeta Master",
  "TDC Internacional",
  "Intercambio",
  "Pago Pendiente",
  "Credito",
  "Sin Pago",
];

export const selectBancos = [
  "",
  "Plaza",
  "Banesco",
  "Venezuela",
  "Bicentenario",
  "Mercantil",
  "Bancamiga",
  "Banplus",
  "Provincial",
  "Caribe",
  "BNC",
  "Vzlano Cdto",
  "Tesoro",
];

export const tipoLab = [
  " ",
  "PROTESIS FIJA (corona metal porcelana)",
  "PROTESIS FIJA (corona metal porcelana dento-gingival)",
  "PROTESIS FIJA (corona metal porcelana sobre implante)",
  "PROTESIS FIJA (corona metal porcelana sobre implante atornillado)",
  "PROTESIS FIJA (corona metal porcelana con hombro ceramico)",
  "PROTESIS FIJA (corona funda metalica)",
  "PROTESIS FIJA (corona con frente estetico)",
  "PROTESIS FIJA (puente maryland)",
  "PROTESIS FIJA (perno colocado directo)",
  "PROTESIS FIJA (perno colocado indirecto)",
  "PROTESIS FIJA (encerado funcional por pieza)",
  "PROTESIS FIJA (vaciado de impresion)",
  "Barra de Zirconio)",
  "Corona  Dento-Gingival  S/I  D-L",
  "Corona  Disilicoto  de  Litio",
  "Carilla .Disilìcato  de  Litio",
  "Incrustación  Disilicato  de Litio",
  "Corona  Zirconio",
  "Caolla  Zirconio",
  "Corono D-L Sobreimplante",
  "Corona Zirconio S/I",
  "Corono Zirconio Dento-Gingival",
  "Corona  de  Cerómero",
  "Carilla de Ceromero",
  "lncrustación de Cerómero",
  "Prótesis total en acrílico superior e inferior",
  "Protesis total caracterizada",
  "Protests total inmediata",
  "Protesis total con palador transporente",
  "Protesis con rejilla prefabricada",
  "Cubeta individual",
  "Rodete de mordida",
  "Rebase de acrílico",
  "CROMO COBALTO (1 a 3 piezas)",
  "CROMO COBALTO (4 a 6 piezas)",
  "CROMO COBALTO (7 a 9 piezas)",
  "CROMO COBALTO (10 en adelante)",
  "Gancho Colado",
  "Soldadura de Pieza con Cajuela",
  "Soldadura Simple Cromo-Cobalto",
  "PROTESIS VALPLAST (1 a 3 piezas unilateral)",
  "PROTESIS VALPLAST (1 a 3 piezas bilateral)",
  "PROTESIS VALPLAST (4 a 6 piezas)",
  "PROTESIS VALPLAST (7 a 9 piezas)",
  "PROTESIS VALPLAST (10 en adelante)",
  "Estructura metalica",
  "PARCIALES DE ACRILICO (1 a 3)",
  "PARCIALES DE ACRILICO (4 a 6 piezas)",
  "PARCIALES DE ACRILICO (7 a 9 piezas)",
  "PARCIALES DE ACRILICO (10 en adelante)",
  "Férula  de acrílico  miorelajante",
  "Férula en Silicon o Blanda",
  "Cubeta de Blanqueomiento",
  "Férula Quirúrigica",
  "Férula Retenedor",
  "REPARACIÓNDE ACRÍLICOS (minimos)",
  "REPARACIÓNDE ACRÍLICOS (transparentes)",
  "REPARACIÓNDE ACRÍLICOS (Agregados de Ganchos)",
  "REPARACIÓNDE ACRÍLICOS (Agregados de dientes por pieza)",
  "Mantenimiento de Acrilicos (limpieza y pulidos)",
  "ORTOPEDIA (Placa Hawley con tornillo)",
  "ORTOPEDIA (Placa Hawley sin tornillo)",
  "ORTOPEDIA (Habito de Lengua)",
  "ORTOPEDIA (Mantenedor de Espacoio)",
  "ORTOPEDIA (Hyrax)",
  "CORONAS Y PUENTES PROVISIONALES EN ACRICLICO (Provisional Termocurada)",
  "CORONAS Y PUENTES PROVISIONALES EN ACRICLICO (Provisional Autocurada)",
  "Barra Hibrida Caracterizada",
  "Barra Hibrida (incluye total)",
  "Barra Metal Porcelana",
  "ACETAL-PEEK (barra hibridad acetal acrilica)",
  "ACETAL-PEEK (barra hibridad peek acrilica)",
  "ACETAL-PEEK (DPR acetal acrilica 1 a 4 piezas)",
  "ACETAL-PEEK (DPR acetal acrilica 5 a 9 piezas)",
  "ACETAL-PEEK (DPR acetal acrilica 9 en adelante)",
  "Modelo 3D",
  "Prototipo 3D",
  "ACRILICO INYECTADO (1 a 3 piezas unilateral)",
  "ACRILICO INYECTADO (2 a 3 piezas bilateral)",
  "ACRILICO INYECTADO (4 a 6 piezas unilateral)",
  "ACRILICO INYECTADO (7 a 9 piezas unilateral)",
  "ACRILICO INYECTADO (10 en adelante)",
]; 
