export const PACIENTE_LIST_REQUEST = 'PACIENTE_LIST_REQUEST';
export const PACIENTE_LIST_SUCCESS = 'PACIENTE_LIST_SUCCESS';
export const PACIENTE_LIST_FAIL = 'PACIENTE_LIST_FAIL';
export const PACIENTE_LIST_RESET = 'PACIENTE_LIST_RESET';

export const PACIENTE_DETAILS_REQUEST = 'PACIENTE_DETAILS_REQUEST';
export const PACIENTE_DETAILS_SUCCESS = 'PACIENTE_DETAILS_SUCCESS';
export const PACIENTE_DETAILS_FAIL = 'PACIENTE_DETAILS_FAIL';
export const PACIENTE_DETAILS_RESET = 'PACIENTE_DETAILS_RESET';

export const PACIENTE_CREATE_REQUEST = 'PACIENTE_CREATE_REQUEST';
export const PACIENTE_CREATE_SUCCESS = 'PACIENTE_CREATE_SUCCESS';
export const PACIENTE_CREATE_FAIL = 'PACIENTE_CREATE_FAIL';
export const PACIENTE_CREATE_RESET = 'PACIENTE_CREATE_RESET';

export const PACIENTE_UPDATE_REQUEST = 'PACIENTE_UPDATE_REQUEST';
export const PACIENTE_UPDATE_SUCCESS = 'PACIENTE_UPDATE_SUCCESS';
export const PACIENTE_UPDATE_FAIL = 'PACIENTE_UPDATE_FAIL';
export const PACIENTE_UPDATE_RESET = 'PACIENTE_UPDATE_RESET';

export const PACIENTE_DELETE_REQUEST = 'PACIENTE_DELETE_REQUEST';
export const PACIENTE_DELETE_SUCCESS = 'PACIENTE_DELETE_SUCCESS';
export const PACIENTE_DELETE_FAIL = 'PACIENTE_DELETE_FAIL';
export const PACIENTE_DELETE_RESET = 'PACIENTE_DELETE_RESET';

export const PACIENTE_ALL_REQUEST = 'PACIENTE_ALL_REQUEST';
export const PACIENTE_ALL_SUCCESS = 'PACIENTE_ALL_SUCCESS';
export const PACIENTE_ALL_FAIL = 'PACIENTE_ALL_FAIL';
export const PACIENTE_ALL_RESET = 'PACIENTE_ALL_RESET';

export const PACIENTE_ADDCONTROL_REQUEST = 'PACIENTE_ADDCONTROL_REQUEST';
export const PACIENTE_ADDCONTROL_SUCCESS = 'PACIENTE_ADDCONTROL_SUCCESS';
export const PACIENTE_ADDCONTROL_FAIL = 'PACIENTE_ADDCONTROL_FAIL';
export const PACIENTE_ADDCONTROL_RESET = 'PACIENTE_ADDCONTROL_RESET';

export const PACIENTE_DELETECONTROL_REQUEST = 'PACIENTE_DELETECONTROL_REQUEST';
export const PACIENTE_DELETECONTROL_SUCCESS = 'PACIENTE_DELETECONTROL_SUCCESS';
export const PACIENTE_DELETECONTROL_FAIL = 'PACIENTE_DELETECONTROL_FAIL';
export const PACIENTE_DELETECONTROL_RESET = 'PACIENTE_DELETECONTROL_RESET';
