export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

export const PRODUCT_REVIEW_CREATE_REQUEST = 'PRODUCT_REVIEW_CREATE_REQUEST';
export const PRODUCT_REVIEW_CREATE_SUCCESS = 'PRODUCT_REVIEW_CREATE_SUCCESS';
export const PRODUCT_REVIEW_CREATE_FAIL = 'PRODUCT_REVIEW_CREATE_FAIL';
export const PRODUCT_REVIEW_CREATE_RESET = 'PRODUCT_REVIEW_CREATE_RESET';

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';
export const PRODUCT_DELETE_RESET = 'PRODUCT_DELETE_RESET';

export const PRODUCT_CATEGORY_LIST_REQUEST = 'PRODUCT_CATEGORY_LIST_REQUEST';
export const PRODUCT_CATEGORY_LIST_SUCCESS = 'PRODUCT_CATEGORY_LIST_SUCCESS';
export const PRODUCT_CATEGORY_LIST_FAIL = 'PRODUCT_CATEGORY_LIST_FAIL';

export const PRODUCT_UPDATE_EXISTENCIA_REQUEST = 'PRODUCT_UPDATE_EXISTENCIA_REQUEST';
export const PRODUCT_UPDATE_EXISTENCIA_SUCCESS = 'PRODUCT_UPDATE_EXISTENCIA_SUCCESS';
export const PRODUCT_UPDATE_EXISTENCIA_FAIL = 'PRODUCT_UPDATE_EXISTENCIA_FAIL';
export const PRODUCT_UPDATE_EXISTENCIA_RESET = 'PRODUCT_UPDATE_EXISTENCIA_RESET';

export const PRODUCT_BYCODE_REQUEST = 'PRODUCT_BYCODE_REQUEST';
export const PRODUCT_BYCODE_SUCCESS = 'PRODUCT_BYCODE_SUCCESS';
export const PRODUCT_BYCODE_FAIL = 'PRODUCT_BYCODE_FAIL';
export const PRODUCT_BYCODE_RESET = 'PRODUCT_BYCODE_RESET';

export const PRODUCT_ALL_REQUEST = 'PRODUCT_ALL_REQUEST';
export const PRODUCT_ALL_SUCCESS = 'PRODUCT_ALL_SUCCESS';
export const PRODUCT_ALL_FAIL = 'PRODUCT_ALL_FAIL';

export const PRODUCT_ONLY_CODES_REQUEST = 'PRODUCT_ONLY_CODES_REQUEST';
export const PRODUCT_ONLY_CODES_SUCCESS = 'PRODUCT_ONLY_SUCCESS';
export const PRODUCT_ONLY_CODES_FAIL = 'PRODUCT_ONLY_FAIL';
