export const QUOTE_CREATE_REQUEST = 'QUOTE_CREATE_REQUEST';
export const QUOTE_CREATE_SUCCESS = 'QUOTE_CREATE_SUCCESS';
export const QUOTE_CREATE_FAIL = 'QUOTE_CREATE_FAIL';
export const QUOTE_CREATE_RESET = 'QUOTE_CREATE_RESET';

export const QUOTE_LIST_REQUEST = 'QUOTE_LIST_REQUEST';
export const QUOTE_LIST_SUCCESS = 'QUOTE_LIST_SUCCESS';
export const QUOTE_LIST_FAIL = 'QUOTE_LIST_FAIL';

export const QUOTE_DETAILS_REQUEST = 'QUOTE_DETAILS_REQUEST';
export const QUOTE_DETAILS_SUCCESS = 'QUOTE_DETAILS_SUCCESS';
export const QUOTE_DETAILS_FAIL = 'QUOTE_DETAILS_FAIL';

export const QUOTE_UPDATE_REQUEST = 'QUOTE_UPDATE_REQUEST';
export const QUOTE_UPDATE_SUCCESS = 'QUOTE_UPDATE_SUCCESS';
export const QUOTE_UPDATE_FAIL = 'QUOTE_UPDATE_FAIL';
export const QUOTE_UPDATE_RESET = 'QUOTE_UPDATE_RESET';