export const SERVICIO_LIST_REQUEST = 'SERVICIO_LIST_REQUEST';
export const SERVICIO_LIST_SUCCESS = 'SERVICIO_LIST_SUCCESS';
export const SERVICIO_LIST_FAIL = 'SERVICIO_LIST_FAIL';

export const SERVICIO_ALL_LIST_REQUEST = 'SERVICIO_LIST_REQUEST';
export const SERVICIO_ALL_LIST_SUCCESS = 'SERVICIO_LIST_SUCCESS';
export const SERVICIO_ALL_LIST_FAIL = 'SERVICIO_LIST_FAIL';

export const SERVICIO_DETAILS_REQUEST = 'SERVICIO_DETAILS_REQUEST';
export const SERVICIO_DETAILS_SUCCESS = 'SERVICIO_DETAILS_SUCCESS';
export const SERVICIO_DETAILS_FAIL = 'SERVICIO_DETAILS_FAIL';

export const SERVICIO_CREATE_REQUEST = 'SERVICIO_CREATE_REQUEST';
export const SERVICIO_CREATE_SUCCESS = 'SERVICIO_CREATE_SUCCESS';
export const SERVICIO_CREATE_FAIL = 'SERVICIO_CREATE_FAIL';
export const SERVICIO_CREATE_RESET = 'SERVICIO_CREATE_RESET';

export const SERVICIO_UPDATE_REQUEST = 'SERVICIO_UPDATE_REQUEST';
export const SERVICIO_UPDATE_SUCCESS = 'SERVICIO_UPDATE_SUCCESS';
export const SERVICIO_UPDATE_FAIL = 'SERVICIO_UPDATE_FAIL';
export const SERVICIO_UPDATE_RESET = 'SERVICIO_UPDATE_RESET';

export const SERVICIO_DELETE_REQUEST = 'SERVICIO_DELETE_REQUEST';
export const SERVICIO_DELETE_SUCCESS = 'SERVICIO_DELETE_SUCCESS';
export const SERVICIO_DELETE_FAIL = 'SERVICIO_DELETE_FAIL';
export const SERVICIO_DELETE_RESET = 'SERVICIO_DELETE_RESET';

export const SERVICIO_BYCODE_REQUEST = 'SERVICIO_BYCODE_REQUEST';
export const SERVICIO_BYCODE_SUCCESS = 'SERVICIO_BYCODE_SUCCESS';
export const SERVICIO_BYCODE_FAIL = 'SERVICIO_BYCODE_FAIL';
export const SERVICIO_BYCODE_RESET = 'SERVICIO_BYCODE_RESET';

export const SERVICIO_ALL_REQUEST = 'SERVICIO_ALL_REQUEST';
export const SERVICIO_ALL_SUCCESS = 'SERVICIO_ALL_SUCCESS';
export const SERVICIO_ALL_FAIL = 'SERVICIO_ALL_FAIL';

export const SERVICIO_ONLY_CODES_REQUEST = 'SERVICIO_ONLY_CODES_REQUEST';
export const SERVICIO_ONLY_CODES_SUCCESS = 'SERVICIO_ONLY_SUCCESS';
export const SERVICIO_ONLY_CODES_FAIL = 'SERVICIO_ONLY_FAIL';
